name: Start Ngrok Tunnel  

on:
  workflow_dispatch:

jobs:

  ngrok:

    runs-on: windows-latest

    steps:
    
    - uses: actions/checkout@v2

    - name: Set Credentials  
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Download Ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract Ngrok
      run: Expand-Archive ngrok.zip

    - name: Authenticate Ngrok
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Validate ngrok  
      run: .\ngrok\ngrok -version

    - name: Check RDP Port
      run: Test-Connection localhost -Port 3389

    - name: Start Tunnel
      run: | 
        .\ngrok\ngrok tcp 3389 --log=stdout
        .\ngrok\ngrok tcp 3389 --log=stdout

    - name: Keep Tunnel Alive  
      run: |
       nohup .\ngrok\ngrok tcp 3389 &
       sleep 86400
