name: Start Ngrok Tunnel

on:
  schedule:
    - cron: '*/30 * * * *'  # Restart every 30 mins  

jobs:

  ngrok:

    runs-on: windows-latest

    steps:
    
    - uses: actions/checkout@v2

    - name: Download Ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract Ngrok
      run: Expand-Archive ngrok.zip

    - name: Authenticate Ngrok
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}  
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

    - name: Enable RDP 
      # Commands to enable remote desktop

    - name: Start Tunnel
      run: .\ngrok\ngrok.exe tcp 3389

    - name: Keep Alive  
      run: sleep 600 # Sleep 10 minutes
