name: Setup Ngrok Tunnel

on:
  workflow_dispatch:

jobs:

  ngrok:

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v2

    - name: Download Ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract Ngrok
      run: Expand-Archive ngrok.zip

    - name: Authenticate Ngrok
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}  
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

    - name: Enable Remote Desktop
      # Commands to enable RDP 

    - name: Start Tunnel
      run: .\ngrok\ngrok.exe tcp 3389 -keepalive 10
            
    - name: Keep Tunnel Alive
      run: |  
        nohup .\ngrok\ngrok.exe tcp 3389 -keepalive 10 &
        sleep 86400
